### ISSUE TITLE
package.json is missing 'chokidar'

### ISSUE THREAD

**Issue by tmtrademark** [SupportClass/lfg-sounds#2]
On a fresh install, nodecg won't start up and appears to be missing "chokidar" from watcher.js. Adding it to package.json fixes things up.

**Comment by Lange** [comment]
Huh, while you're right that this bundle should be shipping its own `chokidar`, it should be pulling in NodeCG's `chokidar`. This is what it does on my instances, which is why I never noticed that it wasn't in this bundle's package.json
